### ISSUE TITLE
There is already a collection named 'todos'

### ISSUE THREAD

**Issue by kennethlynne** [Urigo/angular-meteor-seed#1]
Tried the demo page, it only worked on first page load.

![2014-01-06_1009](https://f.cloud.github.com/assets/390817/1849403/7128e586-76b2-11e3-87dc-1b5f1a0d5480.png)

**Comment by Urigo** [comment]
this seed is deprecated - Official Angular-Meteor library here: https://github.com/Urigo/angular-meteor
