### ISSUE TITLE
Error: ENOENT, no such file or directory

### ISSUE THREAD

**Issue by mshanak** [Urigo/angular-meteor-seed#2]
Error: ENOENT, no such file or directory '/nodeApps/meteor-angular-seed-master/.meteor/local/build/programs/client/app.html'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at packages/angularjs/server.js:15:1

**Comment by Urigo** [comment]
this seed is deprecated - Official Angular-Meteor library here: https://github.com/Urigo/angular-meteor
